services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - '6333:6333'
    volumes:
      - rag_qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: snehasis
      POSTGRES_PASSWORD: snehasis123
      POSTGRES_DB: ragdb
    ports:
      - '5432:5432'
    volumes:
      - rag_postgres_data:/var/lib/postgresql/data

volumes:
  rag_postgres_data:
  rag_qdrant_storage:
