services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - '6333:6333'
    volumes:
      - rag_qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - rag_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.4.0-bookworm
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - rag_redis_data:/data

volumes:
  rag_postgres_data:
  rag_qdrant_storage:
  rag_redis_data:
